image: node:6.4.1

before_script:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install

test:
  script:
      - npm install
      - npm run tslint
      - npm run jslint
      - npm test -- --browsers Chrome